const ENUM_PENDING = "PENDING";
const ENUM_IDLE = "IDLE";
const ENUM_ERROR = "ERROR";
const ENUM_SUCCESS = "SUCCESS";

export const ENUM_LOADING_TYPES = {
  ENUM_PENDING,
  ENUM_IDLE,
  ENUM_ERROR,
  ENUM_SUCCESS,
};
